/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.practise.webScrapper.GUI;

import com.practise.webScrapper.dao.ProductDao;
import com.practise.webScrapper.dao.impl.ProductDaoImpl;
import com.practise.webScrapper.entity.Product;
import com.practise.webScrapper.util.Grabber;
import java.io.IOException;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chira
 */
public class Display extends javax.swing.JFrame {

    DefaultTableModel model;
    ProductDao productDao = new ProductDaoImpl();

    /**
     * Creates new form Main
     */
    public Display(String search) {
        initComponents();
        try {
            System.out.println("Searching ");
            kaymu(search.replace(" ","+"));
            System.out.println("Searching ");
            goGazzab(search.replace(" ","+"));
            System.out.println("Searching ");
            meroShopping(search.replace(" ","-"));
            System.out.println("Adding");
            tableAdd();
        } catch (IOException ioe) {

        }
    }

    public void tableAdd() {
        for (Product p : productDao.getAll()) {

            String name = p.getProductName();
            String price = p.getPrice();
            String dealer = p.getDealer();
            String link = p.getLink();

            Object[] row = {name, price, dealer, link};

            model = (DefaultTableModel) table.getModel();

            model.addRow(row);
        }
    }

    private Display() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Price(Nrs.)", "Dealer", "Link"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setColumnSelectionAllowed(true);
        table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table);
        table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jLabel1.setText("Note:Double Click on link to select link");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        setVisible(false);
        model.setRowCount(0);
        productDao.clearArray();

    }//GEN-LAST:event_backActionPerformed

    public void kaymu(String search) throws IOException {
        String baseUrl = "http://www.kaymu.com.np";
        String link = "http://www.kaymu.com.np/catalog/?q=" + search;
        String regEx = "<a class=\"card-overlay block pr\" href=\"(.*?)\"(.*?)\"Search\" data-track-name=\"(.*?)\"(.*?)local=\"(.*?)\"";
        Pattern pattern = Pattern.compile(regEx);

        Matcher matcher = pattern.matcher(Grabber.grab(link));

        while (matcher.find()) {
            Product product = new Product();
            product.setProductName(matcher.group(3));
            product.setLink(baseUrl + matcher.group(1));
            product.setPrice(matcher.group(5));
            product.setDealer(baseUrl);
            productDao.add(product,search);

        }

    }

    public void meroShopping(String search) throws IOException {
        String baseUrl = "https://www.meroshopping.com/";
        String link = "https://www.meroshopping.com/search/" + search;
        String regEx = "<div class=\"product\" style=\" \">[^>]*<a href=\\\"(.*?)\"(.*?)/>[^>]*>(.*?)</div>[^>]*>(.*?)<";
        Pattern pattern = Pattern.compile(regEx);

        Matcher matcher1 = pattern.matcher(Grabber.grab(link));

        while (matcher1.find()) {
            Product product = new Product();
            product.setProductName(matcher1.group(3));
            product.setLink(baseUrl + matcher1.group(1));
            product.setPrice(matcher1.group(4).replace(" NPR ", ""));
            product.setDealer(baseUrl);
           productDao.add(product,search);

        }
    }

    public void goGazzab(String search) throws IOException {
        String baseUrl = "https://www.gogazzab.com/";
        String link = "http://gogazzab.com/catalogsearch/result/?q=" + search;
        String regEx = "<h2 class=\\\"product-name\"><a href=\\\"(.*?)\" title=\\\"(.*?)\"(.*?)h2>[^>]*<(.*?)>[^>]*<(.*?)>[^>]*<(.*?)/span>[^>]*<(.*?)>[^>]*NPR(.*?)<";
        Pattern pattern = Pattern.compile(regEx);

        Matcher matcher = pattern.matcher(Grabber.grab(link));

        while (matcher.find()) {
            Product product = new Product();
            product.setProductName(matcher.group(2));
            product.setLink(matcher.group(1));
            product.setPrice(matcher.group(8).replace(" ", ""));
            product.setDealer(baseUrl);
            productDao.add(product,search);

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Display().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
